In [306]:
import pandas as pd 
import numpy as np 
import datetime as dt 
import calendar

In [307]:
df = pd.read_excel(r'C:\Users\JenniferA\Downloads\DateConversionExercise.xlsx','Copied Data')

In [308]:
df["Date"] = df["Date"].apply(lambda x: '0' + x[:2] + '0' + x[2:] if len(x) == 8 else x)

In [309]:
df['YYYY/MM/DD'] =df['Date']

In [310]:
#df['Mon'] = pd.to_datetime(df['Month'],format ='%B').dt.month.astype(str)

In [311]:
#df['Mon'] =df['Mon'].apply(lambda x: '0' + x[:1] if len == 1 else x)

In [312]:
df['YYYY/MM/DD'] = pd.to_datetime(df['YYYY/MM/DD'],format = 'mixed')

In [315]:
df.iloc[0:16,2] = df.iloc[0:16,2].dt.strftime('%Y-%d-%m')

In [316]:
df

          Date     Month YYYY/MM/DD
0   08/07/2023      July 2023-07-08
1   09/07/2023      July 2023-07-09
2   08/07/2024      July 2024-07-08
3   09/07/2024      July 2024-07-09
4   08/07/2025      July 2025-07-08
5   09/07/2025      July 2025-07-09
6   08/07/2026      July 2026-07-08
7   09/07/2026      July 2026-07-09
8   08/07/2027      July 2027-07-08
9   09/07/2027      July 2027-07-09
10  08/07/2028      July 2028-07-08
11  09/07/2028      July 2028-07-09
12  08/07/2029      July 2029-07-08
13  09/07/2029      July 2029-07-09
14  08/07/2030      July 2030-07-08
15  09/07/2030      July 2030-07-09
16  2023/10/06   October 2023-10-06
17  2023/10/07   October 2023-10-07
18  2023/10/08   October 2023-10-08
19  2023/10/09   October 2023-10-09
20  2023/10/10   October 2023-10-10
21  2023/10/11   October 2023-10-11
22  2023/10/12   October 2023-10-12
23  2023/10/13   October 2023-10-13
24  2023/11/14  November 2023-11-14
25  2023/11/15  November 2023-11-15
26  2023/11/16  November 2023-11-16
27  2023/11/17  November 2023-11-17
28  2023/11/18  November 2023-11-18
29  2023/11/19  November 2023-11-19
30  2023/11/20  November 2023-11-20
31  2023/11/21  November 2023-11-21
32  2023/11/22  November 2023-11-22
33  2023/11/23  November 2023-11-23
34  2023/11/24  November 2023-11-24
35  2023/11/25  November 2023-11-25
36  2023/11/26  November 2023-11-26
37  2023/11/27  November 2023-11-27
38  07/04/2025      July 2025-07-04
39  07/04/2026      July 2026-07-04
40  07/04/2027      July 2027-07-04
41  07/04/2025      July 2025-07-04
42  06/05/2023      June 2023-06-05
43  08/04/2023    August 2023-08-04
44  07/04/2025      July 2025-07-04
45  07/04/2026      July 2026-07-04
46  07/04/2027      July 2027-07-04
47  07/04/2025      July 2025-07-04
48  06/05/2024      June 2024-06-05
49  08/04/2024    August 2024-08-04
50  07/04/2025      July 2025-07-04
51  07/04/2026      July 2026-07-04
52  07/04/2027      July 2027-07-04
53  07/04/2025      July 2025-07-04